In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv("AI_SocialMedia_Student_Dataset.csv")
dataset

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04
...,...,...,...,...,...,...,...,...,...,...
15995,STU_15996,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,STU_15997,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,STU_15998,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,STU_15999,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,STU_16000,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

In [5]:
# Remove unwanted feature
df=dataset.drop(columns=['Student_ID'])
df

,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04
...,...,...,...,...,...,...,...,...,...
15995,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

In [6]:
# Checking for null or missing value
df.isnull().sum()

Age                          0
Gender                       0
Education_Level              0
Daily_Social_Media_Hours     0
Daily_AI_Tool_Usage_Hours    0
Sleep_Hours                  0
Physical_Activity_Hours      0
Mental_Health_Score          0
Physical_Health_Score        0
dtype: int64

In [7]:
# Converting categorical data into numeric
df = pd.get_dummies(df, dtype= int, drop_first=True)
df

,Age,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Gender_Male,Gender_Non-binary,Education_Level_High School,Education_Level_University
0,19,5.32,1.21,7.30,1.41,74.06,98.90,1,0,0,0
1,16,5.21,3.89,7.81,2.48,76.13,89.94,0,1,1,0
2,25,3.61,2.65,6.34,0.06,65.01,76.75,1,0,0,1
3,23,2.93,1.43,6.12,1.37,74.67,87.38,1,0,0,1
4,20,6.52,1.64,5.23,1.14,67.74,88.04,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
15995,16,3.89,4.67,5.15,1.41,76.64,81.90,0,0,1,0
15996,14,4.42,3.24,5.57,1.52,77.50,96.36,1,0,1,0
15997,15,0.00,2.89,5.56,1.81,77.56,99.58,0,0,1,0
15998,20,0.30,5.09,5.61,1.25,80.69,82.03,0,0,0,0
15999,23,3.18,1.70,6.81,0.18,72.85,82.53,1,0,0,1

In [8]:
#checking dtypes
df.dtypes

Age                              int64
Daily_Social_Media_Hours       float64
Daily_AI_Tool_Usage_Hours      float64
Sleep_Hours                    float64
Physical_Activity_Hours        float64
Mental_Health_Score            float64
Physical_Health_Score          float64
Gender_Male                      int64
Gender_Non-binary                int64
Education_Level_High School      int64
Education_Level_University       int64
dtype: object

In [9]:
# Checking column names
df.columns

Index(['Age', 'Daily_Social_Media_Hours', 'Daily_AI_Tool_Usage_Hours',
       'Sleep_Hours', 'Physical_Activity_Hours', 'Mental_Health_Score',
       'Physical_Health_Score', 'Gender_Male', 'Gender_Non-binary',
       'Education_Level_High School', 'Education_Level_University'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          16000 non-null  int64
 1   Daily_Social_Media_Hours     16000 non-null  float64
 2   Daily_AI_Tool_Usage_Hours    16000 non-null  float64
 3   Sleep_Hours                  16000 non-null  float64
 4   Physical_Activity_Hours      16000 non-null  float64
 5   Mental_Health_Score          16000 non-null  float64
 6   Physical_Health_Score        16000 non-null  float64
 7   Gender_Male                  16000 non-null  int64
 8   Gender_Non-binary            16000 non-null  int64
 9   Education_Level_High School  16000 non-null  int64
 10  Education_Level_University   16000 non-null  int64
dtypes: float64(6), int64(5)
memory usage: 1.3 MB

In [15]:
#converting all decimal values into numberical values - This will avoid the continous values 
df['Sleep_Hours'] = df['Sleep_Hours'].apply(np.int64)
df['Daily_Social_Media_Hours'] = df['Daily_Social_Media_Hours'].apply(np.int64)
df['Daily_AI_Tool_Usage_Hours'] = df['Daily_AI_Tool_Usage_Hours'].apply(np.int64)
df['Physical_Activity_Hours'] = df['Physical_Activity_Hours'].apply(np.int64)
df['Mental_Health_Score'] = df['Mental_Health_Score'].apply(np.int64)
df['Physical_Health_Score'] = df['Physical_Health_Score'].apply(np.int64)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          16000 non-null  int64
 1   Daily_Social_Media_Hours     16000 non-null  int64
 2   Daily_AI_Tool_Usage_Hours    16000 non-null  int64
 3   Sleep_Hours                  16000 non-null  int64
 4   Physical_Activity_Hours      16000 non-null  int64
 5   Mental_Health_Score          16000 non-null  int64
 6   Physical_Health_Score        16000 non-null  int64
 7   Gender_Male                  16000 non-null  int64
 8   Gender_Non-binary            16000 non-null  int64
 9   Education_Level_High School  16000 non-null  int64
 10  Education_Level_University   16000 non-null  int64
dtypes: int64(11)
memory usage: 1.3 MB

In [17]:
# Saving Cleaned Dataset.
df.to_csv("AI_SocialMedia_Student_Dataset_DP.csv",index=False)